/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AircraftCard: typeof import('./src/components/leftPanel/aircraftInfo/AircraftCard.vue')['default']
    AircraftInfo: typeof import('./src/components/leftPanel/aircraftInfo/AircraftInfo.vue')['default']
    AircraftPanel: typeof import('./src/components/AircraftPanel/AircraftPanel.vue')['default']
    AirlineDesign: typeof import('./src/components/leftPanel/airlineDesign/AirlineDesign.vue')['default']
    CameraController: typeof import('./src/components/rightPanel/cameraController/CameraController.vue')['default']
    CesiumViewer: typeof import('./src/components/publicComponents/CesiumViewer.vue')['default']
    ColorDialogs: typeof import('./src/components/publicComponents/ColorDialogs.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ImageCard: typeof import('./src/components/rightPanel/loadedSource/ImageCard.vue')['default']
    LeftPanel: typeof import('./src/components/leftPanel/LeftPanel.vue')['default']
    LineDrawer: typeof import('./src/components/rightPanel/mapDraw/LineDrawer.vue')['default']
    LoadedSource: typeof import('./src/components/rightPanel/loadedSource/LoadedSource.vue')['default']
    MapDraw: typeof import('./src/components/rightPanel/mapDraw/MapDraw.vue')['default']
    PointCloudCard: typeof import('./src/components/rightPanel/loadedSource/PointCloudCard.vue')['default']
    PointDrawer: typeof import('./src/components/rightPanel/mapDraw/PointDrawer.vue')['default']
    PolygonDrawer: typeof import('./src/components/rightPanel/mapDraw/PolygonDrawer.vue')['default']
    RightPanel: typeof import('./src/components/rightPanel/RightPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sheet: typeof import('./src/components/publicComponents/Sheet.vue')['default']
  }
}
